# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#example-using-an-action-in-the-same-repository-as-the-workflow
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: Setup environment
description: prepare for building environment
inputs:
  node-version:
    description: 'Nodejs version for actions/setup-node'
    default: 16

runs:
  using: "composite"
  steps:

    - name: Checkout
      # https://github.com/actions/checkout
      uses: actions/checkout@v2
      with:
        # Number of commits to fetch. 0 indicates all history.
        # all history for changelog
        fetch-depth: 1

    - name: Setup node
      # https://github.com/actions/setup-node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: https://registry.npmjs.org

    - name: Setup pnpm
      # https://github.com/pnpm/action-setup
      uses: pnpm/action-setup@v2.0.1
      with:
        version: 6

    - name: Environment
      shell: bash
      run: |
        set -ex
        git config color.status always
        env
        hostname
        whoami
        node --version
        npm --version
        pnpm --version

    - name: Cache .pnpm-store
      # https://github.com/actions/cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.pnpm-store
          node_modules
        key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm

    - name: Install
      shell: bash
      run: |
        pnpm i --frozen-lockfile
