# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions

# pipeline: build -> test -> changests ···> pull-request
name: Build

on:
  push:
    branches:
      - '*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          - os: ubuntu-latest
            arch: x64

          - os: ubuntu-latest
            arch: arm64

          - os: ubuntu-latest
            arch: arm

          - os: macos-latest
            arch: x64

          - os: macos-latest
            arch: arm64

    name: build - ${{ matrix.target.os }} ${{ matrix.target.arch }}
    runs-on: ${{ matrix.target.os }}

    steps:
      - name: Setup environment
        uses: zthxxx/getrusage.js/.github/actions/setup@master

      - name: Build binding binary
        id: build
        run: |
          pnpm run build:binary -- ${{ matrix.target.arch }}

      - name: Upload artifact
        # https://github.com/actions/upload-artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.build.outputs.target_bin }}
          path: build/${{ steps.build.outputs.target_bin }}
          if-no-files-found: error

  test:
    needs: build

    strategy:
      fail-fast: false
      matrix:
        # only can test with GitHub-hosted runners
        # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
        os:
          - ubuntu-20.04
          - ubuntu-18.04
          - macos-11
          - macos-10.15
        node:
          - 12
          - 14
          - 16

    # all GitHub-hosted runners's arch is x64
    name: test - ${{ matrix.os }} - node v${{ matrix.node }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup environment
        uses: zthxxx/getrusage.js/.github/actions/setup@master
        with:
          node-version: ${{ matrix.node }}
      
      - name: Platform Arch Info
        id: platform
        run: |
          echo "::set-output name=platform::$(node -p '`${process.platform}-${process.arch}`')"

      - name: Download artifacts
        # https://github.com/actions/download-artifact
        uses: actions/download-artifact@v2
        with:
          name: getrusage-${{ steps.platform.outputs.platform }}.node
          path: build

      - name: List artifacts
        # https://stackoverflow.com/questions/16073708/force-git-status-to-output-color-on-the-terminal-inside-a-script
        run: |
          git -c color.status=always status

      - name: Build npm entry
        run: |
          pnpm run build:entry

      - name: Unit Test
        run: |
          pnpm test

  changesets:
    needs: test
    name: Changesets action
    runs-on: ubuntu-latest

    steps:
      - name: Setup environment
        uses: zthxxx/getrusage.js/.github/actions/setup@master

      - name: Clean build path
        # due to `actions/download-artifact` cannot override exists files
        run: |
          rm -rf build

      - name: Download all artifacts
        # https://github.com/actions/download-artifact
        uses: actions/download-artifact@v2
        with:
          path: build

      - name: List artifacts
        # https://stackoverflow.com/questions/16073708/force-git-status-to-output-color-on-the-terminal-inside-a-script
        run: |
          git -c color.status=always status

      - name: Changeset version
        # try to bump version and create pull request
        # https://github.com/changesets/action
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # changeset commit message
          commit: "chore: changeset bump version"
          # changeset pull request title
          title: "chore: changeset bump version"
