# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: build

on:
  push:
    branches:
      - '*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          - os: ubuntu-latest
            arch: x64

          - os: ubuntu-latest
            arch: arm64

          - os: ubuntu-latest
            arch: arm

          - os: macos-latest
            arch: x64

          - os: macos-latest
            arch: arm64

    name: build - ${{ matrix.target.os }} ${{ matrix.target.arch }}
    runs-on: ${{ matrix.target.os }}

    steps:
      - name: Checkout
        # https://github.com/actions/checkout
        uses: actions/checkout@v2
        with:
          # Number of commits to fetch. 0 indicates all history.
          # all history for changelog
          fetch-depth: 0

      - name: Setup node
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org

      - name: Install
        run: |
          env
          node --version
          npm --version
          npm ci

      - name: Build package
        id: build
        run: |
          npm run build -- ${{ matrix.target.arch }}

      - name: Upload artifact
        # https://github.com/actions/upload-artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.build.outputs.target_bin }}
          path: build/${{ steps.build.outputs.target_bin }}
          if-no-files-found: error

  test:
    needs:
      - build

    strategy:
      fail-fast: false
      matrix:
        # only can test with GitHub-hosted runners
        # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
        os:
          - ubuntu-20.04
          - ubuntu-18.04
          - macos-11
          - macos-10.15
        node:
          - 12
          - 14
          - 16

    # all GitHub-hosted runners's arch is x64
    name: test - ${{ matrix.os }} - node v${{ matrix.node }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        # https://github.com/actions/checkout
        uses: actions/checkout@v2
        with:
          # Number of commits to fetch. 0 indicates all history.
          # all history for changelog
          fetch-depth: 0

      - name: Setup node
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.target.node }}
          registry-url: https://registry.npmjs.org

      - name: Install
        run: |
          env
          node --version
          npm i -g npm
          npm --version
          npm ci
      
      - name: Platform Arch Info
        id: platform
        run: |
          echo "::set-output name=platform::$(node -p '`${process.platform}-${process.arch}`')"

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: getrusage-${{ steps.platform.outputs.platform }}.node
          path: .

      - name: List artifacts
        run: |
          git status

      - name: Build npm entry
        run: |
          npm run build:entry

      - name: Unit Test
        run: |
          npm test
